name: Build and push image to docker hub

on:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: set master tag
        if: startsWith(${{github.ref}}, "refs/heads/master")
        run: echo "::set-env name=DOCKER_TAG::latest"
        
      - name: print docker tag
        run: echo "$DOCKER_TAG"

      
