name: Build and push image to docker hub

on:
  push:
    branches: [ master ]
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: print_ref
        run: echo ${{github.ref}}

      
